// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmtPiwIXUElsF0BnLQC7NzRDtFuRbvYc',
    appId: '1:929296353864:web:81411ca3375c998b74667d',
    messagingSenderId: '929296353864',
    projectId: 'fonoapp-3918b',
    authDomain: 'fonoapp-3918b.firebaseapp.com',
    storageBucket: 'fonoapp-3918b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdKdvKJ-A-aYwXPN3xanorgb8kH-lBp0',
    appId: '1:929296353864:android:58aef3d9703f1a3174667d',
    messagingSenderId: '929296353864',
    projectId: 'fonoapp-3918b',
    storageBucket: 'fonoapp-3918b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKqsP4C50Mu9OZPUr5tAO0ocxPn3hSqg',
    appId: '1:929296353864:ios:24d2365da99a01b674667d',
    messagingSenderId: '929296353864',
    projectId: 'fonoapp-3918b',
    storageBucket: 'fonoapp-3918b.firebasestorage.app',
    iosBundleId: 'com.example.fonoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKqsP4C50Mu9OZPUr5tAO0ocxPn3hSqg',
    appId: '1:929296353864:ios:24d2365da99a01b674667d',
    messagingSenderId: '929296353864',
    projectId: 'fonoapp-3918b',
    storageBucket: 'fonoapp-3918b.firebasestorage.app',
    iosBundleId: 'com.example.fonoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWmtPiwIXUElsF0BnLQC7NzRDtFuRbvYc',
    appId: '1:929296353864:web:bc50f64408af52f074667d',
    messagingSenderId: '929296353864',
    projectId: 'fonoapp-3918b',
    authDomain: 'fonoapp-3918b.firebaseapp.com',
    storageBucket: 'fonoapp-3918b.firebasestorage.app',
  );
}
